port: 7891
socks-port: 7892
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: Rule
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
    - 4.2.2.2
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - tls://8.8.4.4
    - tls://1.1.1.1
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
    geosite:
      - gfw
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
  fake-ip-filter:
    - '*.lan'
