port: 7891
socks-port: 7892
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: Rule
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
    - 4.2.2.2
  nameserver:
    - https://dns.zixu.site/dns-query
  fallback:
    - https://dns.zixu.site/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
  fake-ip-filter:
    - '*.lan'
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    - swscan.apple.com
    - mesu.apple.com
    - swquery.apple.com
    - swdownload.apple.com
    - swcdn.apple.com
    - swdist.apple.com
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - 'xbox.*.microsoft.com'
    - 'xbox.*.*.microsoft.com'
    - +.xboxlive.com
    - 'time.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'time.*.apple.com'
    - 'time1.*.com'
    - 'time2.*.com'
    - 'time3.*.com'
    - 'time4.*.com'
    - 'time5.*.com'
    - 'time6.*.com'
    - 'time7.*.com'
    - 'ntp.*.com'
    - 'ntp1.*.com'
    - 'ntp2.*.com'
    - 'ntp3.*.com'
    - 'ntp4.*.com'
    - 'ntp5.*.com'
    - 'ntp6.*.com'
    - 'ntp7.*.com'
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - +.pool.ntp.org
    - time1.cloud.tencent.com
    - lens.l.google.com
    - +.music.163.com
    - +.126.net
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - '*.kuwo.cn'
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - +.y.qq.com
    - +.music.tc.qq.com
    - aqqmusic.tc.qq.com
    - +.stream.qqmusic.qq.com
    - +.xiami.com
    - +.music.migu.cn
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - '+.stun.*.*.*.*.*'
    - +.srv.nintendo.net
    - '*.n.n.srv.nintendo.net'
    - +.stun.playstation.net
    - +.battlenet.com.cn
    - +.wotgame.cn
    - +.wggames.cn
    - +.wowsgame.cn
    - +.wargaming.net
    - '*.square-enix.com'
    - '*.finalfantasyxiv.com'
    - '*.ffxiv.com'
    - '*.ff14.sdo.com'
    - ff.dorado.sdo.com
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - proxy.golang.org
    - +.qq.com
    - +.baidu.com
    - +.163.com
    - +.126.net
    - +.taobao.com
    - +.jd.com
    - +.tmall.com
    - '*.mcdn.bilivideo.cn'
    - +.nvidia.com
    - +.nvidia.cn
    - +.nvgs.nvidia.com
    - +.nvgs.nvidia.cn
    - shark007.net
